from django.conf.urls import include, url, patterns
from teacher import views

urlpatterns = patterns('',
              url(r'^teacher/login/$', views.teacher_login, name="teacher-login"),
              url(r'^teacher/register/$', views.teacher_register, name="teacher-register"),
              url(r'^teacher/$', views.teacher_home, name="teacher-home"),
              url(r'^teacher/manage/(?P<course_uuid>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/$', views.manage_course, name="teacher-manage-course"),
	      url(r'^teacher/change/displayDemoImageVideo/$', views.change_display_image_video, name='teacher-change-display-image-video'),
              url(r'^load_modules/$',views.get_modules,name='load-modules'),
              url(r'^load_week_details/$',views.get_week_details,name='load-week-details'),
              url(r'^teacher/update/course/week/details/$', views.update_courseweek_details, name="teacher-update-course-week-details"),
              url(r'^teacher/update/course/details/$', views.update_course_details, name="teacher-update-course-details"),
              url(r'^upload/course_demo_image/$', views.update_course_demo_image, name="update-course-demo-image"),
              url(r'^teacher/update/course/typeandname/$', views.update_course_type_name, name="teacher-update-course-type-name"),
              url(r'^teacher/delete/module/$', views.delete_course_module, name="delete-course-module"),
              url(r'^teacher/delete/video/$', views.delete_module_video, name="delete-module-video"),
              url(r'^teacher/manage/(?P<course_uuid>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/createquiz/$', views.create_quiz, name="teacher-manage-course-create-quiz"),
              url(r'^getordering/$',views.get_ordering,name="get-ordering"),
              url(r'^teacher/manage/(?P<course_uuid>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/changeordering/$', views.change_ordering, name="teacher-manage-course-change-ordering"),
              url(r'^users/xls/(?P<course_uuid>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/$', views.download_xls, name="xls"),
              url(r'^anaylse/$', views.anaylse, name='anaylse'),
              url(r'^downloadxls/all/$', views.downloadxlsall, name='download-xls-all'),
              url(r'^download/file/(?P<filename>[a-zA-Z0-9\-_]+)/$', views.downloadfile, name='download-file'),
              url(r'^change/testschedules/(?P<course_uuid>[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})/$', views.change_testschedules, name="teacher-manage-course-change-test-schedules"),
              url(r'^isinline/$', views.isInline, name='is-inline'),
              url(r'^gettestlink/$', views.getTestLink, name='get-test-link'),
              url(r'^getinlinetest/$', views.getInlineTestLink, name='get-inlinetest-link'), 
              url(r'^activate/course/$', views.activateCourse, name='activate-course'),
              url(r'^verify/payment/$', views.verify_transaction, name='verify-payment'),
              url(r'^teacher/enroll/student/$', views.rescue_enroll, name='rescue-student-payment'),              
)
