# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_mang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_key', models.CharField(max_length=10, unique=True)),
                ('module_name', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=1)),
                ('test_number', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_for_course', to='course_mang.CourseDetail')),
            ],
        ),
    ]
