# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import teacher.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_mang', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(b'PASS', b'PASS'), (b'PARTICIPATE', b'PARTICIPATE')], default=b'PARTICIPATE', max_length=40)),
                ('max_marks', models.IntegerField(default=0)),
                ('marks_score', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-added_date'],
                'verbose_name': 'Certificate Section',
            },
        ),
        migrations.CreateModel(
            name='EnrolledCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want_notifications', models.BooleanField(default=False)),
                ('is_pass', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolled_detail', to='course_mang.CourseDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses_enrolled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_date'],
                'verbose_name': 'EnrolledCourses Section',
            },
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_picture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid_key', models.TextField(max_length=100)),
                ('full_name', models.TextField(max_length=100)),
                ('otp_code', models.TextField(max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[teacher.validators.phone_regex])),
                ('gender', models.CharField(max_length=10, null=True)),
                ('d_o_b', models.DateField(null=True)),
                ('higher_education', models.TextField(max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('fblink', models.URLField(default=b'')),
                ('glink', models.URLField(default=b'')),
                ('i_agree', models.BooleanField(default=False)),
                ('registration_reminder_count', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_login.Address')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default=b'', max_length=500)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_date'],
                'verbose_name': 'StudentInterests Section',
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_status', models.CharField(choices=[(b'OPEN', b'OPEN'), (b'CLOSE', b'CLOSE')], default=b'CLOSE', max_length=5)),
                ('progress_status', models.CharField(choices=[(b'WAITING', b'WAITING'), (b'COMPLETED', b'COMPLETED'), (b'UNDERPROCESS', b'UNDERPROCESS')], default=b'WAITING', max_length=15)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_progress_week', to='course_mang.CourseWeek')),
                ('enrolled_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_user_course_progress', to='student.EnrolledCourses')),
            ],
            options={
                'verbose_name': 'UserCourseProgress Section',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='enr_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certified_course_enrolled_detail', to='student.EnrolledCourses'),
        ),
    ]
