# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 08:38
from __future__ import unicode_literals

import admin_resumable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('street1', models.TextField(max_length=100)),
                ('street2', models.TextField(blank=True, max_length=100)),
                ('pincode', models.TextField(max_length=6)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('city_state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('iama', models.CharField(max_length=27)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=30)),
                ('inquirytype', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=500)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=200)),
                ('foo', admin_resumable.fields.ModelAdminResumableFileField(upload_to=b'unused')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('module_name', models.CharField(max_length=500)),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
                ('iama', models.CharField(max_length=27)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_login.City'),
        ),
    ]
