# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_mang', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_test_handling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssesmentRegisterdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_status', models.CharField(default=b'NA', max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
                ('registrationStatus_status', models.TextField(max_length=50)),
                ('schedule_key', models.CharField(max_length=100)),
                ('assessment_name', models.CharField(default=b'NA', max_length=100)),
                ('result_status', models.CharField(default=b'WAITING', max_length=10)),
                ('candidate_instance_id', models.IntegerField(default=b'111111')),
                ('finish_mail', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_mang.CourseDetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_test_handling.Tests')),
            ],
            options={
                'ordering': ['updated_date'],
                'verbose_name': 'Assesment Registerd User',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCorrectAnswers', models.FloatField()),
                ('totalQuestion', models.FloatField()),
                ('totalMarks', models.FloatField()),
                ('attemptTime', models.FloatField()),
                ('analysis', models.TextField(max_length=200, null=True)),
                ('totalUnAnswered', models.FloatField()),
                ('percentile', models.FloatField()),
                ('maxMarks', models.FloatField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_date'],
                'verbose_name': 'Attemt Test',
            },
        ),
        migrations.CreateModel(
            name='SectionMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCorrectAnswers', models.FloatField()),
                ('skillName', models.TextField(max_length=200)),
                ('totalMarks', models.FloatField()),
                ('totalQuestion', models.FloatField()),
                ('timeTaken', models.FloatField()),
                ('totalUnAnswered', models.FloatField()),
                ('maxMarks', models.FloatField()),
                ('questions', models.TextField(max_length=200, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesment_engine.Result')),
            ],
            options={
                'ordering': ['updated_date'],
                'verbose_name': 'Section Marks',
            },
        ),
        migrations.CreateModel(
            name='TestMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('test_type', models.CharField(choices=[(b'INLINE', b'INLINE'), (b'MIDTERM', b'MIDTERM'), (b'END_COURSE', b'END_COURSE')], default=b'NOT Avail', max_length=40)),
                ('assesmentRegisterdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesment_engine.AssesmentRegisterdUser')),
            ],
        ),
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=200)),
                ('htmlReport', models.URLField(max_length=500)),
                ('startTime', models.TextField(max_length=100)),
                ('endTime', models.TextField(max_length=100)),
                ('completionMode', models.TextField(max_length=200)),
                ('pdfReport', models.URLField(max_length=500)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assesmentRegisterdUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assesment_engine.AssesmentRegisterdUser')),
            ],
            options={
                'ordering': ['startTime'],
                'verbose_name': 'Test Status',
            },
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('marks_scored', models.FloatField()),
                ('finish_mode', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assesmentRegisterdUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assesment_engine.AssesmentRegisterdUser')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='testStatus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assesment_engine.TestStatus'),
        ),
    ]
